name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: cheesits456/ReactionPics
          ref: gh-pages
        
      - name: Set up Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.x'
        
      - name: Set up environment
        run: git clone https://github.com/cheesits456/ReactionPics.git

      - name: Run Node script
        run: node ./ReactionPics/build.js
          
      - name: Clean up and push branch
        run: |
          rm -rf ./ReactionPics/
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo `git add . && git commit -m "${{ GITHUB_REF.commit.message }}"`
          git push
          echo Done!
