# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.x'
        
      - name: Set up environment
        run: |
          git clone https://github.com/cheesits456/ReactionPics.git
          cd ReactionPics
          git switch gh-pages
          git clone https://github.com/cheesits456/ReactionPics.git

      - name: Run Node script
        run: |
          echo $PWD
          ls
          node ./build.js
